INSERT INTO role (name)
SELECT * FROM (SELECT 'USER') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'USER');

INSERT INTO role (name)
SELECT * FROM (SELECT 'ADMIN') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ADMIN');